language: php

php:
    - 5.6
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist

after_script:
    - ./vendor/bin/coveralls -v
