language: php

php:
    - 5.6
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

before_script: composer install

script: ./vendor/bin/phpunit --configuration tests/php/phpunit.xml
