#
# Service container definition.
#

services:
    oblists:
        class: Itafroma\Zork\State\OblistCollection
        calls:
            - [create, ['INITIAL']]
    atoms:
        class: Itafroma\Zork\State\AtomCollection
